#------------------------------------------------------------------------
# VM setup
#------------------------------------------------------------------------

language: python
python:
 - "2.7"
# - "pypy"

env:
 - TEST_SUITE="-n 2"
 - TEST_SUITE="--test-verilog"
 - TEST_SUITE="-n 2 --dump-vcd"

#------------------------------------------------------------------------
# before dependency installation
#------------------------------------------------------------------------
before_install:
 - ARTIFACTS=http://brg.csl.cornell.edu/artifacts
 - echo $PWD
 - mkdir build

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------
install:

 # Install verilator

 - wget $ARTIFACTS/verilator-travis.tar.gz
 - tar xvfz verilator-travis.tar.gz
 - export VERILATOR_ROOT=$PWD/verilator-3.864
 - export PATH=$VERILATOR_ROOT/bin:$PATH
 - export PYMTL_VERILATOR_INCLUDE_DIR=$VERILATOR_ROOT/include
 - verilator --version

 # Install PARC cross-compiler

 - wget $ARTIFACTS/maven-xcc.tar.bz2
 - tar xvfj maven-xcc.tar.bz2
 - export PATH=$PWD/maven-sys-xcc-0.0-209-g75c3473/bin:$PATH

 # Install Python requirements

 - pip install -e .
 - pip install -r requirements.txt
 - pip install yolk
 - yolk -l

#------------------------------------------------------------------------
# before test runner
#------------------------------------------------------------------------
before_script:

 # Build assembly tests

 - mkdir -p tests/build
 - cd tests/build
 - ../configure --host=maven; cat config.log
 - make

 # Return to build directory

 - cd ../../build

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------
script:
 - py.test .. --verbose --maxfail 20 $TEST_SUITE

# - py.test ../new_proc --verbose -n 4  # Debug
