language: python
python:
 - "2.7"
# - "pypy"

# pre-install commands
before_install:
 - mkdir build
 - mkdir -p build/bin
 - mkdir -p build/lib/gcc
 - mkdir -p build/libexec/gcc

# install necessary dependencies
install:
 - "pip install -r requirements.txt"
 - "wget -P build/bin http://brg.csl.cornell.edu/artifacts/maven-gcc"
 - "wget -P build/bin http://brg.csl.cornell.edu/artifacts/maven-objdump"
 - "wget -P build/bin http://brg.csl.cornell.edu/artifacts/maven-as"
 - "wget -P build/bin http://brg.csl.cornell.edu/artifacts/maven-ld"
 - "wget -P build/bin http://brg.csl.cornell.edu/artifacts/libgcc.a"
 - "chmod 755 build/bin/maven-gcc"
 - "chmod 755 build/bin/maven-objdump"
 - "chmod 755 build/bin/maven-as"
 - "chmod 755 build/bin/maven-ld"
 - "mv build/bin/maven-as build/libexec/gcc/as"
 - "mv build/bin/maven-ld build/libexec/gcc/ld"
 - "mv build/bin/libgcc.a build/lib/gcc"

# command to run tests
before_script:
 - cd build
 - export PATH=$PWD/bin:$PATH
 - maven-gcc -print-search-dirs
 - ls /home/travis/build/dmlockhart/pymtl/build/bin/../libexec/gcc
 - ls /home/travis/build/dmlockhart/pymtl/build/bin/../lib/gcc

# command to run tests
script:
 - py.test .. --verbose
