language: python
python:
 - "2.7"
# - "pypy"

# pre-install commands
before_install: mkdir build

# install necessary dependencies
install:
 - "pip install -r requirements.txt"
 - "wget -P build http://brg.csl.cornell.edu/artifacts/maven-gcc"

# command to run tests
before_script:
 - cd build
 - chmod 755 maven-gcc

# command to run tests
script: py.test .. --verbose
