#------------------------------------------------------------------------
# VM setup
#------------------------------------------------------------------------

language: python
python:
 - "2.7"
# - "pypy"

env:
 - TEST_SUITE="-n 2"
 - TEST_SUITE="--test-verilog"

#------------------------------------------------------------------------
# before dependency installation
#------------------------------------------------------------------------
before_install:
 - mkdir build

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------
install:

 # Install Python requirements

 - pip install -r requirements.txt

 # Install PARC cross-compiler

 - ARTIFACTS=http://brg.csl.cornell.edu/artifacts
 - wget $ARTIFACTS/maven-xcc.tar.bz2
 - tar xvfj maven-xcc.tar.bz2
 - export PATH=$PWD/maven-sys-xcc-0.0-209-g75c3473/bin:$PATH

 # Install verilator

 - wget http://www.veripool.org/ftp/verilator-3.864.tgz
 - tar xvzf verilator*.t*gz
 - cd verilator*
 - export VERILATOR_ROOT=$PWD
 - ./configure
 - make
 - cd ..

#------------------------------------------------------------------------
# before test runner
#------------------------------------------------------------------------
before_script:

 # Build assembly tests

 - mkdir -p tests/build
 - cd tests/build
 - ../configure --host=maven; cat config.log
 - make

 # Return to build directory

 - cd ../../build

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------
script:
 - py.test .. --verbose $TEST_SUITE

# - py.test ../new_proc --verbose -n 4  # Debug
