#=========================================================================
# TravisCI Setup
#=========================================================================

language: python
python:
 - "2.7"

env:
 - CONFIG=""
 - CONFIG="--test-verilog"
 - CONFIG="--dump-vcd"

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:

 # Install verilator

 - wget http://brg.csl.cornell.edu/artifacts/verilator-travis-3.876.tar.gz
 - tar xvfz verilator-travis-3.876.tar.gz
 - export VERILATOR_ROOT=$PWD/verilator-3.876
 - export PATH=$VERILATOR_ROOT/bin:$PATH
 - export PYMTL_VERILATOR_INCLUDE_DIR=$VERILATOR_ROOT/include
 - verilator --version

 # Install Python requirements

 - pip install -e .
 - pip install -r requirements.txt
 - pip install yolk
 - yolk -l

#------------------------------------------------------------------------
# before test runner
#------------------------------------------------------------------------

before_script:

 # Make build directory

 - mkdir -p build
 - cd build

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------

script:
 - py.test .. $CONFIG

