#------------------------------------------------------------------------
# VM setup
#------------------------------------------------------------------------

language: python
python:
 - "2.7"
# - "pypy"

#------------------------------------------------------------------------
# before dependency installation
#------------------------------------------------------------------------
before_install:
 - mkdir build

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------
install:

 # Install Python requirements

 - pip install -r requirements.txt
 - ARTIFACTS=http://brg.csl.cornell.edu/artifacts

 # Install PARC cross-compiler

 - wget $ARTIFACTS/maven-xcc.tar.bz2
 - tar xvfj maven-xcc.tar.bz2
 - export PATH=$PWD/maven-sys-xcc-0.0-209-g75c3473/bin:$PATH

#------------------------------------------------------------------------
# before test runner
#------------------------------------------------------------------------
before_script:

 # Build assembly tests

 - mkdir -p tests/build
 - cd tests/build
 - ../configure --host=maven; cat config.log
 - make

 # Return to build directory

 - cd ../../build

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------
script:
 - py.test .. --verbose -n 4

# - py.test ../new_proc --verbose -n 4  # Debug
